# Generated by Django 4.2.7 on 2023-11-08 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_team_timg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='timg',
            field=models.ImageField(upload_to='pics'),
        ),
    ]
